#!/bin/bash

# This script renames the current branch
# and then creates a new dev branch for doing the next
# round of work.

if [ -z "$1" ]
then
  echo "new branch name is required"
  echo "usage: git-put-away new-branch-name"
  exit
fi

# work/commit on the dev branch
dev=`git branch --no-color | grep \* | cut -d ' ' -f2-`

# tracker branch tracks the remote branch
if [[ ${dev} != *_dev ]]; then
    # default to master
    tracker='master'
else
    # dev branch name has "_dev" suffix
    tracker=${dev%_*}
fi

git checkout ${tracker}
if [ $? -ne 0 ]; then
    echo "failed to checkout tracking branch: ${tracker}"
    exit -1
fi

git branch -m ${dev} $1
git checkout -b ${dev}
git branch
