#!/bin/bash

# work/commit on the dev branch
dev=`git branch --no-color | grep \* | cut -d ' ' -f2-`

# tracker branch tracks the remote branch
if [[ ${dev} != *_dev ]]; then
    # default to master
    tracker='master'
else
    # dev branch name has "_dev" suffix
    tracker=${dev%_*}
fi

git checkout ${tracker}
if [ $? -ne 0 ]; then
    echo "failed to checkout tracking branch: ${tracker}"
    exit -1
fi

git pull
git checkout ${dev}

interactive='-i '
if [ "$1" = "-auto" ]; then
  interactive=''
fi

git rebase ${interactive}${tracker}

