#!/bin/bash

current=`git branch --no-color | grep \* | cut -d ' ' -f2-`

branches=`git branch --list '*_dev' | cut -c 3-`

for branch in ${branches}; do
  git checkout ${branch}
  git-from-git -auto
done

git checkout ${current}

